import asyncio

import httpx
import pytest
import respx

from app import llm, netsafe
from app.models import Citation, Claim, SourceCheck
from app.sources import SourceText, check_citation
from app.textutil import (certainty, find_dois, locate, number_mismatch, numbers, quote_in_text, rank_passages)


# ------------------------------------------------------------------ deterministic core

def test_numbers_normalize():
    assert numbers("более 60 % запросов, 1,5 млн человек, 4 841 статья") == ["60%", "1.5млн", "4841"]
    assert numbers("more than 60 percent") == ["60%"]


def test_number_mismatch_detects_changed_percentage():
    cn, sn, bad = number_mismatch("ИИ-поисковики ошибались в 40% случаев", "incorrect answers to more than 60 percent of queries")
    assert bad and cn == ["40%"] and "60%" in sn


def test_number_mismatch_ok_when_same():
    assert number_mismatch("ошибались в 60% случаев", "more than 60 percent of queries")[2] is False


def test_number_mismatch_ignores_years_only():
    assert number_mismatch("в 2024 году", "in 2023 the study")[2] is False


def test_quote_must_be_verbatim():
    src = "The study found that chatbots provided incorrect answers to more than 60 percent of queries."
    assert quote_in_text("provided incorrect answers to more than 60 percent of queries", src)
    assert quote_in_text("provided  «incorrect» answers to more than 60 percent", src)  # whitespace / quotes tolerated
    # a "quote" with a silently changed number must NOT pass, even though it is 98% similar
    assert not quote_in_text("provided incorrect answers to more than 40 percent of queries", src)
    assert not quote_in_text("chatbots were always correct and reliable in every test", src)


def test_certainty():
    assert certainty("Возможно, это около 30%")[0] == "hedged"
    assert certainty("Доказано, что 74% студентов используют ИИ")[0] == "assertive"
    assert certainty("Столица Казахстана — Астана")[0] == "neutral"


def test_find_dois_and_locate():
    assert find_dois("см. https://doi.org/10.1038/s41598-023-41032-5.") == ["10.1038/s41598-023-41032-5"]
    text = "Первое. Второе предложение про 60% ошибок. Третье."
    s, e = locate("Второе предложение про 60% ошибок.", text)
    assert text[s:e].startswith("Второе")


def test_rank_passages_prefers_numbers():
    ps = ["Погода была хорошей.", "Боты ошибались в 60% случаев по данным исследования.", "Прочее."]
    assert rank_passages("ошибались в 60% случаев", ps, k=1)[0][0] == 1


# ------------------------------------------------------------------ SSRF

@pytest.mark.parametrize("url", ["http://127.0.0.1/x", "http://10.0.0.5/", "http://169.254.169.254/latest/meta-data", "ftp://example.com"])
def test_ssrf_blocked(url):
    with pytest.raises(netsafe.BlockedURL):
        asyncio.run(netsafe.assert_public(url))


# ------------------------------------------------------------------ source existence (network mocked)

@pytest.fixture
def no_dns(monkeypatch):
    async def ok(url):
        return None
    monkeypatch.setattr(netsafe, "assert_public", ok)


@respx.mock
def test_unregistered_doi_is_not_found():
    doi = "10.9999/fake.2024.001"
    respx.get(f"https://doi.org/api/handles/{doi}").mock(return_value=httpx.Response(404, json={"responseCode": 100}))
    respx.get(f"https://api.crossref.org/works/{doi}").mock(return_value=httpx.Response(404))
    respx.get(f"https://api.openalex.org/works/doi:{doi}").mock(return_value=httpx.Response(404))
    sc, _ = asyncio.run(check_citation(Citation(id="S1", kind="academic", doi=doi, title="Anything")))
    assert sc.status == "not_found" and "не зарегистрирован" in sc.detail


@respx.mock
def test_real_doi_pointing_to_other_paper_is_mismatch():
    doi = "10.1038/s41598-023-41032-5"
    respx.get(f"https://doi.org/api/handles/{doi}").mock(return_value=httpx.Response(200, json={"responseCode": 1}))
    respx.get(f"https://api.crossref.org/works/{doi}").mock(return_value=httpx.Response(200, json={"message": {
        "DOI": doi, "title": ["Fabrication and errors in the bibliographic citations generated by ChatGPT"],
        "author": [{"family": "Walters", "given": "William"}, {"family": "Wilder", "given": "Esther"}],
        "issued": {"date-parts": [[2023]]}, "container-title": ["Scientific Reports"]}}))
    respx.get(f"https://api.openalex.org/works/doi:{doi}").mock(return_value=httpx.Response(404))
    cit = Citation(id="S1", kind="academic", doi=doi, title="Large language models improve student grades", authors=["Ivanov A."], year=2021)
    sc, _ = asyncio.run(check_citation(cit))
    assert sc.status == "mismatch"
    assert any("год" in d for d in sc.differences) and any("авторы" in d for d in sc.differences)


@respx.mock
def test_url_404_is_not_found(no_dns):
    respx.get("https://example.org/missing").mock(return_value=httpx.Response(404))
    sc, _ = asyncio.run(check_citation(Citation(id="S1", kind="web", url="https://example.org/missing")))
    assert sc.status == "not_found"


@respx.mock
def test_url_403_is_unreachable_not_fake(no_dns):
    respx.get("https://paywalled.example/a").mock(return_value=httpx.Response(403))
    sc, _ = asyncio.run(check_citation(Citation(id="S1", kind="web", url="https://paywalled.example/a")))
    assert sc.status == "unreachable"


@respx.mock
def test_academic_title_not_in_any_db_is_not_found():
    respx.get("https://api.crossref.org/works").mock(return_value=httpx.Response(200, json={"message": {"items": [
        {"title": ["Completely different topic about soil bacteria"], "DOI": "10.1/x"}]}}))
    respx.get("https://api.openalex.org/works").mock(return_value=httpx.Response(200, json={"results": []}))
    cit = Citation(id="S1", kind="academic", title="Hallucination rates of LLMs in Kazakh universities", year=2023, authors=["Smith J."])
    sc, _ = asyncio.run(check_citation(cit))
    assert sc.status == "not_found"


@respx.mock
def test_book_not_in_db_is_unchecked_not_fake():
    respx.get("https://api.crossref.org/works").mock(return_value=httpx.Response(200, json={"message": {"items": []}}))
    respx.get("https://api.openalex.org/works").mock(return_value=httpx.Response(200, json={"results": []}))
    sc, _ = asyncio.run(check_citation(Citation(id="S1", kind="book", title="История Казахстана, 5 том")))
    assert sc.status == "unchecked"


# ------------------------------------------------------------------ judge guards (LLM mocked)

SOURCE = ("The Tow Center tested eight generative search tools. Collectively, they provided incorrect answers "
          "to more than 60 percent of queries. Grok 3 answered 94 percent of the queries incorrectly.")


def _patch_llm(monkeypatch, out):
    async def fake(system, user, max_tokens=0):
        return out
    monkeypatch.setattr(llm, "complete_json", fake)


def _judge(claim_text):
    from app.judge import judge_cited
    cit = Citation(id="S1", kind="web", url="https://x.org")
    sc = SourceCheck(citation_id="S1", status="exists", method="http", detail="", text_scope="full")
    cl = Claim(id="C1", text=claim_text, citation_ids=["S1"])
    return asyncio.run(judge_cited(cl, [cit], {"S1": sc}, {"S1": SourceText(SOURCE, "full", "https://x.org")}))


def test_fabricated_quote_from_judge_is_dropped(monkeypatch):
    _patch_llm(monkeypatch, {"verdict": "supports", "quote": "all eight tools were accurate in 90 percent of cases", "reason": "ok"})
    r = _judge("Инструменты были точны в 90% случаев")
    assert r.verdict == "unverifiable" and not r.evidence


def test_supports_but_numbers_differ_becomes_contradicted(monkeypatch):
    _patch_llm(monkeypatch, {"verdict": "supports", "quote": "they provided incorrect answers to more than 60 percent of queries", "reason": "Совпадает."})
    r = _judge("ИИ-поисковики ошибались в 40% запросов")
    assert r.verdict == "contradicted" and r.numbers and r.numbers.mismatch


def test_supported_with_verified_quote(monkeypatch):
    _patch_llm(monkeypatch, {"verdict": "supports", "quote": "Grok 3 answered 94 percent of the queries incorrectly", "reason": "Совпадает."})
    r = _judge("Grok 3 ошибся в 94% запросов")
    assert r.verdict == "supported" and r.evidence[0].quote_verified


def test_missing_source_short_circuits():
    from app.judge import judge_cited
    cit = Citation(id="S1", kind="academic", doi="10.9/x")
    sc = SourceCheck(citation_id="S1", status="not_found", method="doi.org", detail="DOI не зарегистрирован.")
    r = asyncio.run(judge_cited(Claim(id="C1", text="x", citation_ids=["S1"]), [cit], {"S1": sc}, {}))
    assert r.verdict == "source_missing"


def test_attack_mode_contradiction_with_verified_quote(monkeypatch):
    from app.judge import judge_attack
    from app.search import Hit
    wiki = ("Байконур — космодром, расположенный на территории Кызылординской области Казахстана. "
            "Арендован Российской Федерацией до 2050 года.")
    hits = [Hit("https://ru.wikipedia.org/wiki/Байконур", "Байконур", wiki, "Байконур область", False)]
    _patch_llm(monkeypatch, {"verdict": "contradicted", "reason": "Байконур в Кызылординской области.",
                             "evidence": [{"passage": "P1", "stance": "contradicts",
                                           "quote": "космодром, расположенный на территории Кызылординской области Казахстана"}]})
    r = asyncio.run(judge_attack(Claim(id="C1", text="Байконур находится в Карагандинской области"), hits))
    assert r.verdict == "contradicted" and r.evidence[0].quote_verified and r.mode == "attack"


def test_attack_mode_invented_quote_is_not_enough(monkeypatch):
    from app.judge import judge_attack
    from app.search import Hit
    hits = [Hit("https://ru.wikipedia.org/wiki/X", "X", "Совсем другой текст о погоде в горах и туризме.", "q", True)]
    _patch_llm(monkeypatch, {"verdict": "contradicted", "reason": "?", "evidence": [
        {"passage": "P1", "stance": "contradicts", "quote": "Байконур находится в Кызылординской области"}]})
    r = asyncio.run(judge_attack(Claim(id="C1", text="Байконур находится в Карагандинской области"), hits))
    assert r.verdict == "unverifiable" and not r.evidence


def test_search_keywords_keep_ids_and_names():
    from app.search import keywords
    kw = keywords("The MITRE ATT&CK identifier for Kerberoasting is T1558.003").split()
    assert "T1558.003" in kw and "Kerberoasting" in kw and "for" not in kw


def test_source_tiers():
    from app.search import tier_of
    assert tier_of("attack.mitre.org") == "official"
    assert tier_of("ru.wikipedia.org") == "reference"
    assert tier_of("some-seo-blog.com") == "other"


MITRE = ("Adversaries may abuse a valid Kerberos ticket-granting ticket (TGT) or sniff network traffic to obtain a ticket-granting "
         "service (TGS) ticket that may be vulnerable to Brute Force. Kerberoasting is technique T1558.003 in MITRE ATT&CK.")


def _attack_supported(monkeypatch, url):
    from app.judge import judge_attack
    from app.search import Hit
    hits = [Hit(url, "Kerberoasting", MITRE, "Kerberoasting T1558.003", False)]
    _patch_llm(monkeypatch, {"verdict": "supported", "reason": "Совпадает.", "evidence": [
        {"passage": "P1", "stance": "supports", "quote": "Kerberoasting is technique T1558.003 in MITRE ATT&CK"}]})
    return asyncio.run(judge_attack(Claim(id="C1", text="Kerberoasting — это техника T1558.003 в MITRE ATT&CK"), hits))


def test_attack_supported_by_official_source(monkeypatch):
    r = _attack_supported(monkeypatch, "https://attack.mitre.org/techniques/T1558/003/")
    assert r.verdict == "supported" and r.evidence[0].tier == "official" and r.search and r.search.pages == 1


def test_attack_single_weak_site_is_not_enough(monkeypatch):
    r = _attack_supported(monkeypatch, "https://random-blog.net/kerberoasting")
    assert r.verdict == "unverifiable" and "одном сайте" in r.reason


def test_extract_fixes_duplicate_ids_and_links_by_markers(monkeypatch):
    from app import extract as ex
    text = ("По данным Tow Center, ИИ-поисковики ошиблись в 60% запросов [1]. Perplexity ошибался в 37% случаев [1].\n\n"
            "Walters и Wilder (2023) выяснили, что 55% ссылок GPT-3.5 выдуманы [2].\n\n"
            "[1] https://www.niemanlab.org/2025/03/study/\n"
            "[2] Walters (2023). https://doi.org/10.1038/s41598-023-41032-5")
    async def fake(system, user, max_tokens=0):
        # niemanlab missing from the LLM output: the URL safety net adds it, it must still become S1
        return {"citations": [{"id": "S2", "url": "https://doi.org/10.1038/s41598-023-41032-5"},
                              {"id": "S2", "raw": "Walters duplicate"}],
                "claims": [{"span": "ИИ-поисковики ошиблись в 60% запросов", "text": "a", "citation_ids": []},
                           {"span": "Perplexity ошибался в 37% случаев", "text": "b", "citation_ids": ["S2"]},
                           {"span": "55% ссылок GPT-3.5 выдуманы", "text": "c", "citation_ids": ["S2"]}]}
    monkeypatch.setattr(llm, "complete_json", fake)
    claims, cits = asyncio.run(ex.extract(text))
    by_id = {c.id: c for c in cits}
    assert len(by_id) == len(cits)  # ids unique
    assert "niemanlab" in by_id["S1"].url and by_id["S2"].doi
    assert [c.citation_ids for c in claims] == [["S1"], ["S1"], ["S2"]]
    assert ex._marker_numbers("a [1] b [2, 3] c [4–6]") == [1, 2, 3, 4, 5, 6]


def test_attack_mode_survives_malformed_evidence(monkeypatch):
    from app.judge import judge_attack
    from app.search import Hit
    hits = [Hit("https://ru.wikipedia.org/wiki/X", "X", "Казахстан — крупнейшая страна без выхода к морю.", "q", False)]
    _patch_llm(monkeypatch, {"verdict": "supported", "reason": "?", "evidence": ["P1", None]})
    r = asyncio.run(judge_attack(Claim(id="C1", text="Казахстан — крупнейшая страна без выхода к морю"), hits))
    assert r.verdict == "unverifiable" and not r.evidence
