import asyncio

import httpx
import pytest
import respx

from app import llm, netsafe
from app.models import Citation, Claim, SourceCheck
from app.sources import SourceText, check_citation
from app.textutil import (certainty, find_dois, locate, number_mismatch, numbers, quote_in_text, rank_passages)


# ------------------------------------------------------------------ deterministic core

def test_numbers_normalize():
    assert numbers("более 60 % запросов, 1,5 млн человек, 4 841 статья") == ["60%", "1.5млн", "4841"]
    assert numbers("more than 60 percent") == ["60%"]


def test_number_mismatch_detects_changed_percentage():
    cn, sn, bad = number_mismatch("ИИ-поисковики ошибались в 40% случаев", "incorrect answers to more than 60 percent of queries")
    assert bad and cn == ["40%"] and "60%" in sn


def test_number_mismatch_ok_when_same():
    assert number_mismatch("ошибались в 60% случаев", "more than 60 percent of queries")[2] is False


def test_number_mismatch_ignores_years_only():
    assert number_mismatch("в 2024 году", "in 2023 the study")[2] is False


def test_quote_must_be_verbatim():
    src = "The study found that chatbots provided incorrect answers to more than 60 percent of queries."
    assert quote_in_text("provided incorrect answers to more than 60 percent of queries", src)
    assert quote_in_text("provided  «incorrect» answers to more than 60 percent", src)  # whitespace / quotes tolerated
    # a "quote" with a silently changed number must NOT pass, even though it is 98% similar
    assert not quote_in_text("provided incorrect answers to more than 40 percent of queries", src)
    assert not quote_in_text("chatbots were always correct and reliable in every test", src)


def test_certainty():
    assert certainty("Возможно, это около 30%")[0] == "hedged"
    assert certainty("Доказано, что 74% студентов используют ИИ")[0] == "assertive"
    assert certainty("Столица Казахстана — Астана")[0] == "neutral"


def test_find_dois_and_locate():
    assert find_dois("см. https://doi.org/10.1038/s41598-023-41032-5.") == ["10.1038/s41598-023-41032-5"]
    text = "Первое. Второе предложение про 60% ошибок. Третье."
    s, e = locate("Второе предложение про 60% ошибок.", text)
    assert text[s:e].startswith("Второе")


def test_rank_passages_prefers_numbers():
    ps = ["Погода была хорошей.", "Боты ошибались в 60% случаев по данным исследования.", "Прочее."]
    assert rank_passages("ошибались в 60% случаев", ps, k=1)[0][0] == 1


# ------------------------------------------------------------------ SSRF

@pytest.mark.parametrize("url", ["http://127.0.0.1/x", "http://10.0.0.5/", "http://169.254.169.254/latest/meta-data", "ftp://example.com"])
def test_ssrf_blocked(url):
    with pytest.raises(netsafe.BlockedURL):
        asyncio.run(netsafe.assert_public(url))


# ------------------------------------------------------------------ source existence (network mocked)

@pytest.fixture
def no_dns(monkeypatch):
    async def ok(url):
        return None
    monkeypatch.setattr(netsafe, "assert_public", ok)


@respx.mock
def test_unregistered_doi_is_not_found():
    doi = "10.9999/fake.2024.001"
    respx.get(f"https://doi.org/api/handles/{doi}").mock(return_value=httpx.Response(404, json={"responseCode": 100}))
    respx.get(f"https://api.crossref.org/works/{doi}").mock(return_value=httpx.Response(404))
    respx.get(f"https://api.openalex.org/works/doi:{doi}").mock(return_value=httpx.Response(404))
    sc, _ = asyncio.run(check_citation(Citation(id="S1", kind="academic", doi=doi, title="Anything")))
    assert sc.status == "not_found" and "не зарегистрирован" in sc.detail


@respx.mock
def test_real_doi_pointing_to_other_paper_is_mismatch():
    doi = "10.1038/s41598-023-41032-5"
    respx.get(f"https://doi.org/api/handles/{doi}").mock(return_value=httpx.Response(200, json={"responseCode": 1}))
    respx.get(f"https://api.crossref.org/works/{doi}").mock(return_value=httpx.Response(200, json={"message": {
        "DOI": doi, "title": ["Fabrication and errors in the bibliographic citations generated by ChatGPT"],
        "author": [{"family": "Walters", "given": "William"}, {"family": "Wilder", "given": "Esther"}],
        "issued": {"date-parts": [[2023]]}, "container-title": ["Scientific Reports"]}}))
    respx.get(f"https://api.openalex.org/works/doi:{doi}").mock(return_value=httpx.Response(404))
    cit = Citation(id="S1", kind="academic", doi=doi, title="Large language models improve student grades", authors=["Ivanov A."], year=2021)
    sc, _ = asyncio.run(check_citation(cit))
    assert sc.status == "mismatch"
    assert any("год" in d for d in sc.differences) and any("авторы" in d for d in sc.differences)


@respx.mock
def test_url_404_is_not_found(no_dns):
    respx.get("https://example.org/missing").mock(return_value=httpx.Response(404))
    sc, _ = asyncio.run(check_citation(Citation(id="S1", kind="web", url="https://example.org/missing")))
    assert sc.status == "not_found"


@respx.mock
def test_url_403_is_unreachable_not_fake(no_dns):
    respx.get("https://paywalled.example/a").mock(return_value=httpx.Response(403))
    sc, _ = asyncio.run(check_citation(Citation(id="S1", kind="web", url="https://paywalled.example/a")))
    assert sc.status == "unreachable"


@respx.mock
def test_academic_title_not_in_any_db_is_not_found():
    respx.get("https://api.crossref.org/works").mock(return_value=httpx.Response(200, json={"message": {"items": [
        {"title": ["Completely different topic about soil bacteria"], "DOI": "10.1/x"}]}}))
    respx.get("https://api.openalex.org/works").mock(return_value=httpx.Response(200, json={"results": []}))
    cit = Citation(id="S1", kind="academic", title="Hallucination rates of LLMs in Kazakh universities", year=2023, authors=["Smith J."])
    sc, _ = asyncio.run(check_citation(cit))
    assert sc.status == "not_found"


@respx.mock
def test_book_not_in_db_is_unchecked_not_fake():
    respx.get("https://api.crossref.org/works").mock(return_value=httpx.Response(200, json={"message": {"items": []}}))
    respx.get("https://api.openalex.org/works").mock(return_value=httpx.Response(200, json={"results": []}))
    sc, _ = asyncio.run(check_citation(Citation(id="S1", kind="book", title="История Казахстана, 5 том")))
    assert sc.status == "unchecked"


# ------------------------------------------------------------------ judge guards (LLM mocked)

SOURCE = ("The Tow Center tested eight generative search tools. Collectively, they provided incorrect answers "
          "to more than 60 percent of queries. Grok 3 answered 94 percent of the queries incorrectly.")


def _patch_llm(monkeypatch, out):
    async def fake(system, user, max_tokens=0, role="judge"):
        return out
    monkeypatch.setattr(llm, "complete_json", fake)


def _judge(claim_text):
    from app.judge import judge_cited
    cit = Citation(id="S1", kind="web", url="https://x.org")
    sc = SourceCheck(citation_id="S1", status="exists", method="http", detail="", text_scope="full")
    cl = Claim(id="C1", text=claim_text, citation_ids=["S1"])
    return asyncio.run(judge_cited(cl, [cit], {"S1": sc}, {"S1": SourceText(SOURCE, "full", "https://x.org")}))


def test_fabricated_quote_from_judge_is_dropped(monkeypatch):
    _patch_llm(monkeypatch, {"verdict": "supports", "quote": "all eight tools were accurate in 90 percent of cases", "reason": "ok"})
    r = _judge("Инструменты были точны в 90% случаев")
    assert r.verdict == "unverifiable" and not r.evidence


def test_supports_but_numbers_differ_becomes_contradicted(monkeypatch):
    _patch_llm(monkeypatch, {"verdict": "supports", "quote": "they provided incorrect answers to more than 60 percent of queries", "reason": "Совпадает."})
    r = _judge("ИИ-поисковики ошибались в 40% запросов")
    assert r.verdict == "contradicted" and r.numbers and r.numbers.mismatch


def test_supported_with_verified_quote(monkeypatch):
    _patch_llm(monkeypatch, {"verdict": "supports", "quote": "Grok 3 answered 94 percent of the queries incorrectly", "reason": "Совпадает."})
    r = _judge("Grok 3 ошибся в 94% запросов")
    assert r.verdict == "supported" and r.evidence[0].quote_verified


def test_missing_source_short_circuits():
    from app.judge import judge_cited
    cit = Citation(id="S1", kind="academic", doi="10.9/x")
    sc = SourceCheck(citation_id="S1", status="not_found", method="doi.org", detail="DOI не зарегистрирован.")
    r = asyncio.run(judge_cited(Claim(id="C1", text="x", citation_ids=["S1"]), [cit], {"S1": sc}, {}))
    assert r.verdict == "source_missing"


def test_attack_mode_contradiction_with_verified_quote(monkeypatch):
    from app.judge import judge_attack
    from app.search import Hit
    wiki = ("Байконур — космодром, расположенный на территории Кызылординской области Казахстана. "
            "Арендован Российской Федерацией до 2050 года.")
    hits = [Hit("https://ru.wikipedia.org/wiki/Байконур", "Байконур", wiki, "Байконур область", False)]
    _patch_llm(monkeypatch, {"verdict": "contradicted", "reason": "Байконур в Кызылординской области.",
                             "evidence": [{"passage": "P1", "stance": "contradicts",
                                           "quote": "космодром, расположенный на территории Кызылординской области Казахстана"}]})
    r = asyncio.run(judge_attack(Claim(id="C1", text="Байконур находится в Карагандинской области"), hits))
    assert r.verdict == "contradicted" and r.evidence[0].quote_verified and r.mode == "attack"


def test_attack_mode_invented_quote_is_not_enough(monkeypatch):
    from app.judge import judge_attack
    from app.search import Hit
    hits = [Hit("https://ru.wikipedia.org/wiki/X", "X", "Совсем другой текст о погоде в горах и туризме.", "q", True)]
    _patch_llm(monkeypatch, {"verdict": "contradicted", "reason": "?", "evidence": [
        {"passage": "P1", "stance": "contradicts", "quote": "Байконур находится в Кызылординской области"}]})
    r = asyncio.run(judge_attack(Claim(id="C1", text="Байконур находится в Карагандинской области"), hits))
    assert r.verdict == "unverifiable" and not r.evidence


def test_search_keywords_keep_ids_and_names():
    from app.search import keywords
    kw = keywords("The MITRE ATT&CK identifier for Kerberoasting is T1558.003").split()
    assert "T1558.003" in kw and "Kerberoasting" in kw and "for" not in kw


def test_source_tiers():
    from app.search import tier_of
    assert tier_of("attack.mitre.org") == "official"
    assert tier_of("ru.wikipedia.org") == "reference"
    assert tier_of("some-seo-blog.com") == "other"


MITRE = ("Adversaries may abuse a valid Kerberos ticket-granting ticket (TGT) or sniff network traffic to obtain a ticket-granting "
         "service (TGS) ticket that may be vulnerable to Brute Force. Kerberoasting is technique T1558.003 in MITRE ATT&CK.")


def _attack_supported(monkeypatch, url):
    from app.judge import judge_attack
    from app.search import Hit
    hits = [Hit(url, "Kerberoasting", MITRE, "Kerberoasting T1558.003", False)]
    _patch_llm(monkeypatch, {"verdict": "supported", "reason": "Совпадает.", "evidence": [
        {"passage": "P1", "stance": "supports", "quote": "Kerberoasting is technique T1558.003 in MITRE ATT&CK"}]})
    return asyncio.run(judge_attack(Claim(id="C1", text="Kerberoasting — это техника T1558.003 в MITRE ATT&CK"), hits))


def test_attack_supported_by_official_source(monkeypatch):
    r = _attack_supported(monkeypatch, "https://attack.mitre.org/techniques/T1558/003/")
    assert r.verdict == "supported" and r.evidence[0].tier == "official" and r.search and r.search.pages == 1


def test_attack_single_weak_site_is_not_enough(monkeypatch):
    r = _attack_supported(monkeypatch, "https://random-blog.net/kerberoasting")
    assert r.verdict == "unverifiable" and "одном сайте" in r.reason


def test_extract_fixes_duplicate_ids_and_links_by_markers(monkeypatch):
    from app import extract as ex
    text = ("По данным Tow Center, ИИ-поисковики ошиблись в 60% запросов [1]. Perplexity ошибался в 37% случаев [1].\n\n"
            "Walters и Wilder (2023) выяснили, что 55% ссылок GPT-3.5 выдуманы [2].\n\n"
            "[1] https://www.niemanlab.org/2025/03/study/\n"
            "[2] Walters (2023). https://doi.org/10.1038/s41598-023-41032-5")
    async def fake(system, user, max_tokens=0, role="judge"):
        # niemanlab missing from the LLM output: the URL safety net adds it, it must still become S1
        return {"citations": [{"id": "S2", "url": "https://doi.org/10.1038/s41598-023-41032-5"},
                              {"id": "S2", "raw": "Walters duplicate"}],
                "claims": [{"span": "ИИ-поисковики ошиблись в 60% запросов", "text": "a", "citation_ids": []},
                           {"span": "Perplexity ошибался в 37% случаев", "text": "b", "citation_ids": ["S2"]},
                           {"span": "55% ссылок GPT-3.5 выдуманы", "text": "c", "citation_ids": ["S2"]}]}
    monkeypatch.setattr(llm, "complete_json", fake)
    claims, cits = asyncio.run(ex.extract(text))
    by_id = {c.id: c for c in cits}
    assert len(by_id) == len(cits)  # ids unique
    assert "niemanlab" in by_id["S1"].url and by_id["S2"].doi
    assert [c.citation_ids for c in claims] == [["S1"], ["S1"], ["S2"]]
    assert ex._marker_numbers("a [1] b [2, 3] c [4–6]") == [1, 2, 3, 4, 5, 6]


def test_attack_mode_survives_malformed_evidence(monkeypatch):
    from app.judge import judge_attack
    from app.search import Hit
    hits = [Hit("https://ru.wikipedia.org/wiki/X", "X", "Казахстан — крупнейшая страна без выхода к морю.", "q", False)]
    _patch_llm(monkeypatch, {"verdict": "supported", "reason": "?", "evidence": ["P1", None]})
    r = asyncio.run(judge_attack(Claim(id="C1", text="Казахстан — крупнейшая страна без выхода к морю"), hits))
    assert r.verdict == "unverifiable" and not r.evidence


NIEMAN = [
    "Last summer, I reported that ChatGPT frequently hallucinated fake URLs to news sites. Research has continued to show that "
    "these citation issues are chronic across the AI industry. On March 6, researchers at the Tow Center for Digital Journalism "
    "at Columbia University added new hard numbers.",
    "For their study, they conducted 200 tests on eight different AI search engines: ChatGPT Search, Perplexity, Perplexity Pro, "
    "Gemini, DeepSeek Search, Grok-2 Search, Grok-3 Search, and Copilot.",
    "Each test query provided the search engine with a quote from an article. Across the 1600 test queries, the search engines "
    "failed to retrieve the correct information more than 60% of the time.",
    "Perplexity, which brands itself as a tool for research, had the lowest failure rate. Grok-3 Search had the highest failure rate.",
    "The chatbot, which is available to X Premium+ subscribers, until recently cost $40 per month.",
    "Another problem outlined by the Tow Center researchers is how confidently these AI search engines are wrong.",
    "Gemini and Grok 3 were the worst offenders, as the only two chatbots that provided more fabricated links than correct links.",
    "The Tow Center report comes just as attention is paid to the failure of AI search engines to drive traffic to news publishers.",
]


def test_rank_surfaces_same_quantity_with_other_number_cross_language():
    # ru claim with "40%", en source says "60%": BM25 alone buries it, the same-unit bonus must bring it up
    top = rank_passages("По данным Tow Center, ИИ-поисковики дали неверные ответы на 40% запросов", NIEMAN, k=3)
    assert 2 in [i for i, _ in top]


def test_same_quantity_other_number_is_contradicted(monkeypatch):
    from app.judge import judge_cited
    text = " ".join(NIEMAN)
    _patch_llm(monkeypatch, {"verdict": "contradicts", "reason": "В источнике более 60%, а не 40%.",
                             "quote": "the search engines failed to retrieve the correct information more than 60% of the time"})
    cit = Citation(id="S2", kind="web", url="https://www.niemanlab.org/x")
    sc = SourceCheck(citation_id="S2", status="exists", method="http", detail="", text_scope="full")
    cl = Claim(id="C2", text="ИИ-поисковики дали неверные ответы на 40% запросов", citation_ids=["S2"])
    r = asyncio.run(judge_cited(cl, [cit], {"S2": sc}, {"S2": SourceText(text, "full", "https://www.niemanlab.org/x")}))
    assert r.verdict == "contradicted" and "60%" in r.evidence[0].quote and r.numbers and "40%" in r.numbers.claim_numbers


def test_quote_with_ellipsis_needs_every_piece_verbatim():
    src = ("Perplexity had the lowest failure rate, answering incorrectly 37% of the time. "
           "Meanwhile, Grok-3 Search had the highest failure rate at 94%.")
    assert quote_in_text("Grok-3 Search had the highest failure rate at 94%. ... Perplexity had the lowest failure rate", src)
    assert not quote_in_text("Grok-3 Search had the highest failure rate at 94%. ... Perplexity was accurate in 90% of cases", src)


def test_reordered_sentences_count_only_if_each_is_verbatim():
    src = ("Perplexity had the lowest failure rate, answering incorrectly 37% of the time. "
           "Meanwhile, Grok-3 Search had the highest failure rate at 94%.")
    assert quote_in_text("Meanwhile, Grok-3 Search had the highest failure rate at 94%. Perplexity had the lowest failure rate, "
                         "answering incorrectly 37% of the time.", src)
    assert not quote_in_text("Meanwhile, Grok-3 Search had the highest failure rate at 94%. Perplexity was always right.", src)


def test_extract_numbers_reference_without_url_by_title(monkeypatch):
    from app import extract as ex
    text = ("Студенты с ChatGPT чаще сдают работы с выдуманными источниками [4].\n\n"
            "[4] Johnson, M., & Patel, R. (2023). The illusion of accuracy: hallucinated references. Computers & Education, 195.")
    async def fake(system, user, max_tokens=0, role="judge"):
        return {"citations": [{"id": "4", "title": "The illusion of accuracy: hallucinated references",
                               "raw": "Johnson, M., & Patel, R. (2023). The illusion of accuracy: hallucinated references."}],
                "claims": [{"span": "Студенты с ChatGPT чаще сдают работы с выдуманными источниками", "text": "x", "citation_ids": ["4"]}]}
    monkeypatch.setattr(llm, "complete_json", fake)
    claims, cits = asyncio.run(ex.extract(text))
    assert [c.id for c in cits] == ["S4"] and claims[0].citation_ids == ["S4"]


def test_title_similarity_subtitle_is_same_work():
    from app.sources import title_similarity
    assert title_similarity("Molecular structure of nucleic acids",
                            "Molecular Structure of Nucleic Acids: A Structure for Deoxyribose Nucleic Acid") >= 88
    assert title_similarity("Programming Is Hard - Or at Least It Used to Be: Educational Opportunities and Challenges",
                            "Programming Is Hard - Or at Least It Used to Be") >= 88
    assert title_similarity("Deep learning for student performance prediction", "Deep learning") < 80


def test_llm_switches_model_when_daily_quota_is_gone(monkeypatch):
    from app.config import settings
    monkeypatch.setattr(settings, "llm_provider", "openai")
    monkeypatch.setattr(settings, "llm_model_judge", "m-a,m-b")
    monkeypatch.setattr(settings, "llm_api_key", "k")
    monkeypatch.setattr(llm, "_exhausted", set())
    used = []
    async def fake_call(system, user, max_tokens, ep, role):
        used.append(ep.model)
        if ep.model == "m-a":
            raise llm.RateLimited("429 GenerateRequestsPerDayPerProjectPerModel-FreeTier", 30, daily=True)
        return '{"verdict": "supports"}'
    monkeypatch.setattr(llm, "_openai_compatible", fake_call)
    assert asyncio.run(llm.complete_json("s", "u"))["verdict"] == "supports"
    assert used == ["m-a", "m-b"] and asyncio.run(llm.complete_json("s", "u")) and used[-1] == "m-b"


def test_llm_falls_back_across_providers(monkeypatch):
    from app.config import settings
    monkeypatch.setattr(settings, "llm_provider", "gemini")
    monkeypatch.setattr(settings, "gemini_api_key", "g-key")
    monkeypatch.setattr(settings, "groq_api_key", "q-key")
    monkeypatch.setattr(settings, "llm_model_judge", "gemini:g-1,groq:openai/gpt-oss-120b,openrouter:x")
    monkeypatch.setattr(llm, "_exhausted", set())
    chain = llm.endpoints_for("judge")
    assert [(e.provider, e.key) for e in chain] == [("gemini", "g-key"), ("groq", "q-key")]  # openrouter has no key
    assert "groq.com" in chain[1].base_url
    seen = []
    async def fake_call(system, user, max_tokens, ep, role):
        seen.append(ep.name)
        if ep.provider == "gemini":
            raise llm.RateLimited("quota PerDay", 30, daily=True)
        return '{"ok": true}'
    monkeypatch.setattr(llm, "_openai_compatible", fake_call)
    assert asyncio.run(llm.complete_json("s", "u")) == {"ok": True}
    assert seen == ["gemini:g-1", "groq:openai/gpt-oss-120b"]


def test_citation_markers_are_not_precise_numbers():
    tone, markers = certainty("Студенты в 3 раза чаще сдают работы с несуществующими источниками [4].")
    assert tone == "assertive" and markers == ["точное число 3"]


def test_attribution_without_url_doi_year_is_not_a_citation(monkeypatch):
    from app import extract as ex
    text = "По данным Бюро национальной статистики, ВВП Казахстана вырос на 6,5% в 2025 году."
    async def fake(system, user, max_tokens=0, role="judge"):
        return {"citations": [{"id": "S1", "raw": "Бюро национальной статистики", "kind": "other"}],
                "claims": [{"span": "ВВП Казахстана вырос на 6,5% в 2025 году", "text": "ВВП вырос на 6,5%", "citation_ids": ["S1"]}]}
    monkeypatch.setattr(llm, "complete_json", fake)
    claims, cits = asyncio.run(ex.extract(text))
    assert cits == [] and claims[0].citation_ids == [] and claims[0].queries  # goes to web search instead


def test_messages_follow_the_check_language():
    from app import i18n
    from app.judge import _in_lang
    from app.prompts import JUDGE_CITED_SYSTEM
    for lang, word in (("ru", "не существует"), ("en", "does not exist"), ("kk", "жоқ")):
        token = i18n.LANG.set(lang)
        try:
            assert word in i18n.tr("src.doi_missing", doi="10.1/x")
            assert i18n.LLM_LANGUAGE[lang] in _in_lang(JUDGE_CITED_SYSTEM)
        finally:
            i18n.LANG.reset(token)
    token = i18n.LANG.set("en")
    try:
        assert i18n.headline(4, 2, 0, 1, 1, 5, 0) == "2 of 4 sources do not exist; 1 claim contradicts the sources."
    finally:
        i18n.LANG.reset(token)
    assert i18n.headline(4, 2, 0, 0, 0, 0, 0) == "2 из 4 источников не существуют."
    assert all(set(v) >= {"ru", "en", "kk"} for v in i18n.MESSAGES.values())


def test_cache_key_keeps_russian_and_separates_other_languages():
    from app.store import text_key
    assert text_key("abc") == text_key("abc", "", "ru") != text_key("abc", "", "en") != text_key("abc", "", "kk")
