"""«Проверить работу перед сдачей»: reading files, finding and parsing the reference list, picking cited claims."""
import io

import pytest
from docx import Document
from fastapi.testclient import TestClient

from app.bibliography import (NO_BIBLIOGRAPHY, Reference, cited_claims, find_bibliography, parse_reference, score,
                              split_references)
from app.documents import DocumentError, extract_text
from app.models import SourceCheck

GOST = """Введение
Рынок цифровых услуг растёт на 12% в год [1, с. 25]. Доля онлайн-продаж составила 40% [2].
Эта фраза без ссылки не должна попасть в проверку.

Список использованных источников
1. Иванов И. И. Цифровая экономика Казахстана / И. И. Иванов // Вестник КазНУ. Серия экономическая. — 2021. — № 3. — С. 45–52.
2. Петров П. П. Основы маркетинга : учебник. — М. : Наука, 2019. — 320 с.
3. Бюро национальной статистики [Электронный ресурс]. — URL: https://stat.gov.kz/ru/ (дата обращения: 01.03.2025).

Приложение А
Таблица 1. Не ссылка.
"""

APA = """Walters and Wilder report that 55% of references were fabricated (Walters & Wilder, 2023).
Older work found similar problems in citation quality (Smith, 2020; Walters, 2023).

References
Walters, W. H., & Wilder, E. I. (2023). Fabrication and errors in the bibliographic citations generated by ChatGPT.
Scientific Reports, 13, 14045. https://doi.org/10.1038/s41598-023-41032-5

Smith, J. (2020). Citation quality in student papers. Oxford University Press.
"""

BRACKETS = """ИИ-поисковики ошибались более чем в 60% запросов по данным Tow Center [1].
Студенты с ChatGPT в три раза чаще сдают работы с несуществующими источниками [2].

Список литературы
[1] https://www.niemanlab.org/2025/03/ai-search-engines-fail-to-produce-accurate-citations/
[2] Johnson, M., & Patel, R. (2023). The illusion of accuracy: hallucinated references in student use of ChatGPT. Computers & Education, 195, 104712.
"""


def _parsed(text):
    body, bib = find_bibliography(text)
    refs = split_references(bib)
    return body, refs, [parse_reference(r)[0] for r in refs]


def test_gost_numbered_list():
    body, refs, cits = _parsed(GOST)
    assert [r.n for r in refs] == [1, 2, 3]  # «Приложение А» cut off
    assert cits[0].kind == "academic" and cits[0].title == "Цифровая экономика Казахстана"
    assert cits[0].year == 2021 and cits[0].venue.startswith("Вестник КазНУ") and cits[0].authors == ["Иванов"]
    assert cits[1].kind == "book" and cits[1].year == 2019
    assert cits[2].kind == "web" and cits[2].url == "https://stat.gov.kz/ru/" and not cits[2].venue
    claims = cited_claims(body, cits)
    assert [c.citation_ids for c in claims] == [["S1"], ["S2"]]
    assert "[1, с. 25]" not in claims[0].text and "12%" in claims[0].text


def test_apa_unnumbered_list_with_wrapped_lines():
    body, refs, cits = _parsed(APA)
    assert len(refs) == 2 and refs[0].raw.endswith("s41598-023-41032-5")  # continuation line joined
    assert cits[0].doi == "10.1038/s41598-023-41032-5" and cits[0].authors == ["Walters", "Wilder"]
    assert cits[0].title == "Fabrication and errors in the bibliographic citations generated by ChatGPT"
    assert cits[1].title == "Citation quality in student papers" and cits[1].kind == "book"
    claims = cited_claims(body, cits)
    assert claims[0].citation_ids == ["S1"]
    assert set(claims[1].citation_ids) == {"S1", "S2"}  # (Smith, 2020; Walters, 2023)


def test_bracket_numbered_list():
    body, refs, cits = _parsed(BRACKETS)
    assert [r.n for r in refs] == [1, 2]
    assert cits[0].kind == "web" and "niemanlab.org" in cits[0].url
    assert cits[1].kind == "academic" and cits[1].venue == "Computers & Education"
    assert [c.citation_ids for c in cited_claims(body, cits)] == [["S1"], ["S2"]]


def test_last_heading_wins_and_missing_list():
    text = "Литература по теме обширна.\nЛитература\nнеправильный заголовок\n\nСписок литературы\n1. Иванов И. И. Книга о важном. — М., 2020."
    _, bib = find_bibliography(text)
    assert "Иванов" in bib and "неправильный" not in bib
    assert find_bibliography("Просто текст без списка литературы. [1]") is None


def test_unparsed_reference_is_flagged_for_llm():
    _, ok = parse_reference(Reference(1, "Какой-то материал из интернета без года"))
    assert not ok


def test_score_counts():
    mk = lambda s: SourceCheck(citation_id="S1", status=s, method="x", detail="")  # noqa: E731
    sc = score([mk("exists"), mk("exists"), mk("not_found"), mk("mismatch"), mk("unreachable"), mk("unchecked")], 6)
    assert sc == {"verified": 2, "total": 6, "fabricated": 1, "distorted": 1, "unreachable": 2}


# ---------------------------------------------------------------- files

def _docx_bytes(paragraphs, table=None) -> bytes:
    doc = Document()
    for p in paragraphs:
        doc.add_paragraph(p)
    if table:
        t = doc.add_table(rows=len(table), cols=len(table[0]))
        for i, row in enumerate(table):
            for j, cell in enumerate(row):
                t.cell(i, j).text = cell
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _pdf_bytes(lines) -> bytes:
    """Minimal one-page PDF with a text layer (Helvetica, ASCII)."""
    esc = lambda s: s.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")  # noqa: E731
    stream = "BT /F1 11 Tf 14 TL 50 760 Td " + " ".join(f"({esc(ln)}) Tj T*" for ln in lines) + " ET"
    objs = [
        "<< /Type /Catalog /Pages 2 0 R >>",
        "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
        f"<< /Length {len(stream)} >>\nstream\n{stream}\nendstream",
        "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    out, offsets = "%PDF-1.4\n", []
    for i, o in enumerate(objs, 1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n{o}\nendobj\n"
    xref = len(out)
    out += f"xref\n0 {len(objs) + 1}\n0000000000 65535 f \n" + "".join(f"{o:010d} 00000 n \n" for o in offsets)
    out += f"trailer\n<< /Size {len(objs) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF"
    return out.encode("latin-1")


def test_docx_paragraphs_and_tables_in_order():
    data = _docx_bytes(["Рост составил 12% [1].", "Список литературы",
                        "1. Иванов И. И. Цифровая экономика Казахстана // Вестник КазНУ. — 2021. — № 3."],
                       table=[["Показатель", "Значение"], ["Рост", "12%"]])
    text = extract_text("курсовая.docx", data)
    assert text.index("Рост составил") < text.index("Список литературы") < text.index("Показатель | Значение")
    assert find_bibliography(text)


def test_pdf_text_layer():
    text = extract_text("paper.pdf", _pdf_bytes([
        "AI search engines were wrong in more than 60% of queries [1].", "References",
        "[1] Walters, W. H. (2023). Fabrication and errors. Scientific Reports, 13, 14045."]))
    body, bib = find_bibliography(text)
    assert "60%" in body and "Walters" in bib


def test_scanned_pdf_and_bad_inputs():
    with pytest.raises(DocumentError, match="картинка"):
        extract_text("scan.pdf", _pdf_bytes([]))
    with pytest.raises(DocumentError, match="формат"):
        extract_text("work.odt", b"x" * 100)
    with pytest.raises(DocumentError, match="пустой"):
        extract_text("work.txt", b"   ")
    with pytest.raises(DocumentError, match="повреждён"):
        extract_text("work.docx", b"not a zip at all")
    assert extract_text("w.txt", "Список литературы\n1. Тест".encode("cp1251")).startswith("Список литературы")


def test_check_file_endpoint_errors():
    from app.main import app
    c = TestClient(app)
    r = c.post("/api/check-file", files={"file": ("w.odt", b"x" * 50, "application/octet-stream")})
    assert r.status_code == 422 and "формат" in r.json()["detail"]
    r = c.post("/api/check-file", files={"file": ("w.txt", "Текст без списка литературы, но длинный.".encode(), "text/plain")})
    assert r.status_code == 422 and r.json()["detail"] == NO_BIBLIOGRAPHY
    assert c.get("/api/sample-docx").status_code == 200
